# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('rec', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('send_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('photos', models.ImageField(null=True, upload_to='profile_pic/%y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=20, null=True)),
                ('last', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=15, null=True)),
                ('day', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('ppic', models.ImageField(blank=True, null=True, upload_to='ppic/%y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('videofile', models.FileField(upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Wpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('msg', models.CharField(blank=True, max_length=500, null=True)),
                ('wpic', models.ImageField(blank=True, null=True, upload_to='wpic/%y%m%d')),
                ('wvid', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
