# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpost',
            name='upic',
            field=models.FileField(null=True, upload_to='upic'),
        ),
    ]
