# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0002_wpost_upic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ppic',
            field=models.ImageField(upload_to='ppic/%y%m%d'),
        ),
    ]
