# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0003_auto_20190331_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpost',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
