# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0004_wpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
