# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetup', '0005_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpost',
            name='status',
        ),
        migrations.AddField(
            model_name='wpost',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
